# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"#\n\x13NotificationRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\"5\n\x14NotificationResponse\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"U\n\x18NotificationListResponse\x12\x39\n\rnotifications\x18\x01 \x03(\x0b\x32\".notification.NotificationResponse\"\x07\n\x05\x45mpty2\xc4\x01\n\x13NotificationService\x12Y\n\x10GetNotifications\x12!.notification.NotificationRequest\x1a\".notification.NotificationResponse\x12R\n\x13GetAllNotifications\x12\x13.notification.Empty\x1a&.notification.NotificationListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFICATIONREQUEST']._serialized_start=36
  _globals['_NOTIFICATIONREQUEST']._serialized_end=71
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=73
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=126
  _globals['_NOTIFICATIONLISTRESPONSE']._serialized_start=128
  _globals['_NOTIFICATIONLISTRESPONSE']._serialized_end=213
  _globals['_EMPTY']._serialized_start=215
  _globals['_EMPTY']._serialized_end=222
  _globals['_NOTIFICATIONSERVICE']._serialized_start=225
  _globals['_NOTIFICATIONSERVICE']._serialized_end=421
# @@protoc_insertion_point(module_scope)
