# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x1f\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"/\n\x0cUserResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"5\n\x10UserListResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.user.UserResponse\"\x07\n\x05\x45mpty2z\n\x0bUserService\x12\x37\n\x0eGetUserDetails\x12\x11.user.UserRequest\x1a\x12.user.UserResponse\x12\x32\n\x0bGetAllUsers\x12\x0b.user.Empty\x1a\x16.user.UserListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERREQUEST']._serialized_start=20
  _globals['_USERREQUEST']._serialized_end=51
  _globals['_USERRESPONSE']._serialized_start=53
  _globals['_USERRESPONSE']._serialized_end=100
  _globals['_USERLISTRESPONSE']._serialized_start=102
  _globals['_USERLISTRESPONSE']._serialized_end=155
  _globals['_EMPTY']._serialized_start=157
  _globals['_EMPTY']._serialized_end=164
  _globals['_USERSERVICE']._serialized_start=166
  _globals['_USERSERVICE']._serialized_end=288
# @@protoc_insertion_point(module_scope)
